const API='http://127.0.0.1:17836/api/v1',$=s=>document.querySelector(s);let token='',state={groups:[],bookmarks:[]},currentURL='';
async function request(path,options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json','X-BookmarkHub-Token':token,...(options.headers||{})}});if(!response.ok){let message=`连接失败 (${response.status})`;try{message=(await response.json()).error||message}catch{}throw Error(message)}return response.json()}
function show(message,error=false){$('#message').textContent=message;$('#message').className=error?'error':''}
function groupPath(id){const names=[],seen=new Set;while(id&&!seen.has(id)){seen.add(id);const group=state.groups.find(g=>g.id===id);if(!group)break;names.unshift(group.name);id=group.parentId}return names.join('/')}
async function flushQueue(){const saved=await chrome.storage.local.get('pendingBookmarks'),queue=saved.pendingBookmarks||[];if(!queue.length)return;const remaining=[];for(const item of queue){try{await request('/bookmarks',{method:'POST',body:JSON.stringify(item)})}catch{remaining.push(item)}}await chrome.storage.local.set({pendingBookmarks:remaining})}
async function connect(){try{state=await request('/state');await flushQueue();$('#pairing').hidden=true;$('#bookmarkForm').hidden=false;$('#state').textContent='已连接本地 Core';const existing=state.bookmarks.find(b=>b.url===currentURL),form=$('#bookmarkForm');if(existing){form.id.value=existing.id;form.title.value=existing.title;form.groupPath.value=groupPath(existing.groupId);form.tagsText.value=(existing.tags||[]).join(', ');form.notes.value=existing.notes||'';form.color.value=existing.color||'';form.starred.checked=!!existing.starred;show('此页面已收藏，保存后将更新')}$('#groups').innerHTML=state.groups.map(g=>`<option value="${groupPath(g.id).replaceAll('"','&quot;')}">`).join('');const tags=new Set(state.bookmarks.flatMap(b=>b.tags||[]));$('#tags').innerHTML=[...tags].map(t=>`<option value="${t.replaceAll('"','&quot;')}">`).join('')}catch(error){$('#pairing').hidden=false;$('#bookmarkForm').hidden=true;$('#state').textContent='Core 未配对';show(error.message,true)}}
async function init(){const saved=await chrome.storage.local.get(['pairingToken','lastGroupPath','lastTags']),[tab]=await chrome.tabs.query({active:true,currentWindow:true});token=saved.pairingToken||'';currentURL=tab?.url||'';const form=$('#bookmarkForm');form.url.value=currentURL;form.title.value=tab?.title||currentURL;form.groupPath.value=saved.lastGroupPath||'';form.tagsText.value=saved.lastTags||'';if(token)await connect();else{$('#pairing').hidden=false;$('#state').textContent='需要配对'}}
$('#pair').onclick=async()=>{token=$('#token').value.trim();await chrome.storage.local.set({pairingToken:token});await connect()};
$('#manager').onclick=()=>chrome.tabs.create({url:'http://127.0.0.1:17836/'});
$('#bookmarkForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target)),payload={id:values.id,url:values.url,title:values.title,groupPath:values.groupPath,tags:values.tagsText.split(/[,，]/),notes:values.notes,color:values.color,starred:event.target.elements.starred.checked};$('.save').disabled=true;try{await request('/bookmarks',{method:'POST',body:JSON.stringify(payload)});await chrome.storage.local.set({lastGroupPath:values.groupPath,lastTags:values.tagsText});show('✓ 已保存');setTimeout(()=>close(),600)}catch(error){const saved=await chrome.storage.local.get('pendingBookmarks'),queue=saved.pendingBookmarks||[];queue.push(payload);await chrome.storage.local.set({pendingBookmarks:queue});show('Core 暂不可用，已在扩展中排队',true);$('.save').disabled=false}};
init();
