const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let data={groups:[],bookmarks:[]},status={},view={group:'',tag:'',query:'',sort:'recent'};

async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){let message=`请求失败 (${response.status})`;try{message=(await response.json()).error||message}catch{}throw Error(message)}return response.headers.get('content-type')?.includes('json')?response.json():response}
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const groupById=id=>data.groups.find(g=>g.id===id);
function groupPath(id){const names=[],seen=new Set;while(id&&!seen.has(id)){seen.add(id);const group=groupById(id);if(!group)break;names.unshift(group.name);id=group.parentId}return names.join('/')}
function descendants(id){const ids=new Set([id]);let changed=true;while(changed){changed=false;data.groups.forEach(group=>{if(ids.has(group.parentId)&&!ids.has(group.id)){ids.add(group.id);changed=true}})}return ids}
function orderedGroups(){const result=[];function walk(parent='',depth=0){data.groups.filter(g=>(g.parentId||'')===parent).sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name)).forEach(group=>{result.push({...group,depth});walk(group.id,depth+1)})}walk();return result}
function groupCount(id){const ids=descendants(id);return data.bookmarks.filter(b=>ids.has(b.groupId)).length}
function domain(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}

function renderGroups(){const all=`<div class="nav-item ${view.group?'':'active'}" data-group=""><span>▦</span><span>全部书签</span><span class="count">${data.bookmarks.length}</span></div>`;$('#groups').innerHTML=all+orderedGroups().map(group=>`<div class="nav-item ${view.group===group.id?'active':''}" data-group="${esc(group.id)}" style="padding-left:${8+group.depth*13}px"><span>▸</span><span>${esc(group.name)}</span><span><button class="tree-action" data-edit-group="${esc(group.id)}">•••</button><span class="count">${groupCount(group.id)}</span></span></div>`).join('')}
function renderTags(){const counts=new Map;data.bookmarks.forEach(bookmark=>bookmark.tags?.forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1)));$('#tags').innerHTML=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([tag,count])=>`<button class="tag ${view.tag===tag?'active':''}" data-tag="${esc(tag)}">${esc(tag)} · ${count}</button>`).join('')||'<span class="hint">暂无标签</span>';$('#tagNames').innerHTML=[...counts.keys()].map(tag=>`<option value="${esc(tag)}">`).join('');$('#clearTag').hidden=!view.tag}
function filtered(){const allowed=view.group?descendants(view.group):null,q=view.query.trim().toLowerCase();return data.bookmarks.filter(bookmark=>(!allowed||allowed.has(bookmark.groupId))&&(!view.tag||bookmark.tags?.includes(view.tag))&&(!q||[bookmark.title,bookmark.url,bookmark.notes,...(bookmark.tags||[]),groupPath(bookmark.groupId)].join(' ').toLowerCase().includes(q))).sort((a,b)=>view.sort==='title'?a.title.localeCompare(b.title):view.sort==='domain'?domain(a.url).localeCompare(domain(b.url)):new Date(b.updatedAt)-new Date(a.updatedAt))}
function renderList(){const rows=filtered(),group=groupById(view.group);$('#viewTitle').textContent=group?groupPath(group.id):view.tag?`标签：${view.tag}`:view.query?'搜索结果':'全部书签';$('#resultMeta').textContent=`${rows.length} 个结果 · 共 ${data.bookmarks.length} 个书签`;$('#activeFilters').innerHTML=[view.group&&`<span class="filter">分组：${esc(groupPath(view.group))}</span>`,view.tag&&`<span class="filter">标签：${esc(view.tag)}</span>`,view.query&&`<span class="filter">搜索：${esc(view.query)}</span>`].filter(Boolean).join('');$('#list').innerHTML=rows.length?rows.map(bookmark=>`<article class="card"><div class="card-head"><div class="favicon">${esc((domain(bookmark.url)[0]||'?').toUpperCase())}</div><div class="card-title"><a href="${esc(bookmark.url)}" target="_blank" rel="noopener">${esc(bookmark.title)}</a><div class="domain">${esc(domain(bookmark.url))}</div></div><div class="card-actions"><button data-edit="${esc(bookmark.id)}">•••</button></div></div>${bookmark.notes?`<p class="notes">${esc(bookmark.notes)}</p>`:''}<div class="card-bottom"><div class="card-tags">${(bookmark.tags||[]).map(tag=>`<button class="tag" data-tag="${esc(tag)}">${esc(tag)}</button>`).join('')}</div><span class="group-path">${esc(groupPath(bookmark.groupId)||'未分组')}</span></div><div class="card-bottom"><span></span><span><button data-copy="${esc(bookmark.id)}">复制</button><button data-delete="${esc(bookmark.id)}" class="danger">删除</button></span></div></article>`).join(''):'<div class="empty"><strong>没有匹配的书签</strong><br>可以清除筛选条件或添加新书签</div>'}
function render(){renderGroups();renderTags();renderList();$('#groupPaths').innerHTML=orderedGroups().map(group=>`<option value="${esc(groupPath(group.id))}">`).join('')}

async function load(){[status,data]=await Promise.all([api('/api/v1/status'),api('/api/v1/state')]);$('#connection').textContent=`${status.deviceFile} · ${data.bookmarks.length} 个书签`;render()}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2200)}
function openBookmark(bookmark={}){const form=$('#bookmarkForm');form.reset();form.elements.id.value=bookmark.id||'';form.elements.title.value=bookmark.title||'';form.elements.url.value=bookmark.url||'';form.elements.groupPath.value=groupPath(bookmark.groupId)||'';form.elements.tagsText.value=(bookmark.tags||[]).join(', ');form.elements.notes.value=bookmark.notes||'';$('#bookmarkDialog').showModal()}
function openGroup(group={}){const form=$('#groupForm');form.reset();form.elements.id.value=group.id||'';form.elements.name.value=group.name||'';form.elements.parentSelect.innerHTML='<option value="">顶层分组</option>'+orderedGroups().filter(g=>g.id!==group.id&&!descendants(group.id||'__none__').has(g.id)).map(g=>`<option value="${esc(g.id)}">${esc(groupPath(g.id))}</option>`).join('');form.elements.parentSelect.value=group.parentId||view.group||'';$('#deleteGroup').hidden=!group.id;$('#groupDialog').showModal()}

$('#groups').onclick=event=>{const edit=event.target.closest('[data-edit-group]');if(edit){event.stopPropagation();openGroup(groupById(edit.dataset.editGroup));return}const item=event.target.closest('[data-group]');if(item){view.group=item.dataset.group;render()}};
$('#tags').onclick=event=>{const item=event.target.closest('[data-tag]');if(item){view.tag=view.tag===item.dataset.tag?'':item.dataset.tag;render()}};
$('#list').onclick=async event=>{const edit=event.target.closest('[data-edit]')?.dataset.edit,remove=event.target.closest('[data-delete]')?.dataset.delete,copy=event.target.closest('[data-copy]')?.dataset.copy,tag=event.target.closest('[data-tag]')?.dataset.tag;if(tag){view.tag=tag;render();return}if(edit)openBookmark(data.bookmarks.find(b=>b.id===edit));if(copy){await navigator.clipboard.writeText(data.bookmarks.find(b=>b.id===copy).url);toast('网址已复制')}if(remove&&confirm('确定删除这个书签？')){await api('/api/v1/bookmarks/delete',{method:'POST',body:JSON.stringify({id:remove})});await load();toast('书签已删除')}};
$('#search').oninput=event=>{view.query=event.target.value;renderList()};$('#sort').onchange=event=>{view.sort=event.target.value;renderList()};$('#clearTag').onclick=()=>{view.tag='';render()};$('#newBookmark').onclick=()=>openBookmark();$('#newGroup').onclick=()=>openGroup();
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('#search').focus()}});
$$('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());

$('#bookmarkForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));await api('/api/v1/bookmarks',{method:'POST',body:JSON.stringify({id:values.id,url:values.url,title:values.title,groupPath:values.groupPath,tags:values.tagsText.split(/[,，]/),notes:values.notes})});$('#bookmarkDialog').close();await load();toast('书签已保存')};
$('#groupForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));await api('/api/v1/groups',{method:'POST',body:JSON.stringify({id:values.id,name:values.name,parentId:values.parentSelect,order:0})});$('#groupDialog').close();await load();toast('分组已保存')};
$('#deleteGroup').onclick=async()=>{const id=$('#groupForm').elements.id.value;if(id&&confirm('删除这个分组？其中的书签和子分组将移动到上一级。')){await api('/api/v1/groups/delete',{method:'POST',body:JSON.stringify({id})});$('#groupDialog').close();view.group='';await load();toast('分组已删除')}};

$('#settingsButton').onclick=()=>{const form=$('#settingsForm');form.elements.syncDir.value=status.syncDir;form.elements.token.value=status.pairingToken;form.elements.deviceFile.value=status.deviceFile;$('#settingsDialog').showModal()};
$('#copyToken').onclick=async()=>{await navigator.clipboard.writeText($('#settingsForm').elements.token.value);toast('配对令牌已复制')};
$('#settingsForm').onsubmit=async event=>{event.preventDefault();const path=event.target.elements.syncDir.value;await api('/api/v1/settings/sync-dir',{method:'POST',body:JSON.stringify({path})});$('#settingsDialog').close();await load();toast('同步目录已更新')};

$('#importButton').onclick=()=>$('#importDialog').showModal();
$('#importForm').onsubmit=async event=>{event.preventDefault();const file=event.target.elements.file.files[0],mode=event.target.elements.mode.value;if(!file)return;const format=file.name.toLowerCase().match(/\.(xbel|xml)$/)?'xbel':'html';await api('/api/v1/import',{method:'POST',body:JSON.stringify({format,mode,content:await file.text()})});$('#importDialog').close();event.target.reset();await load();toast('导入完成')};
$('#exportHtml').onclick=()=>location.href='/api/v1/export?format=html';$('#exportXbel').onclick=()=>location.href='/api/v1/export?format=xbel';

load().catch(error=>{$('#connection').textContent=error.message;toast(error.message)});setInterval(()=>load().catch(()=>{}),5000);
