const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function savedCollapsed(){try{return new Set(JSON.parse(localStorage.getItem('bookmarkhub.collapsedGroups')||'[]'))}catch{return new Set}}
const savedView=localStorage.getItem('bookmarkhub.bookmarkView');
const bookmarkColors={red:'#e05252',orange:'#e07a2d',yellow:'#c99a13',green:'#35a269',cyan:'#269da8',blue:'#477fe5',purple:'#8559d9',pink:'#d85b91'};
let data={groups:[],bookmarks:[]},status={},view={group:'',tag:'',query:'',sort:'recent',starred:false,display:savedView==='list'?'list':'card',collapsed:savedCollapsed()};
let draggedGroup='';

async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){let message=`请求失败 (${response.status})`;try{message=(await response.json()).error||message}catch{}throw Error(message)}return response.headers.get('content-type')?.includes('json')?response.json():response}
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const groupById=id=>data.groups.find(g=>g.id===id);
function groupPath(id){const names=[],seen=new Set;while(id&&!seen.has(id)){seen.add(id);const group=groupById(id);if(!group)break;names.unshift(group.name);id=group.parentId}return names.join('/')}
function descendants(id){const ids=new Set([id]);let changed=true;while(changed){changed=false;data.groups.forEach(group=>{if(ids.has(group.parentId)&&!ids.has(group.id)){ids.add(group.id);changed=true}})}return ids}
function orderedGroups(){const result=[];function walk(parent='',depth=0){data.groups.filter(g=>(g.parentId||'')===parent).sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name)).forEach(group=>{result.push({...group,depth});walk(group.id,depth+1)})}walk();return result}
function groupVisible(group){let parent=group.parentId;while(parent){if(view.collapsed.has(parent))return false;parent=groupById(parent)?.parentId||''}return true}
function groupCount(id){const ids=descendants(id);return data.bookmarks.filter(b=>ids.has(b.groupId)).length}
function domain(url){try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}}

function renderGroups(){const all=`<div class="nav-item ${!view.group&&!view.starred?'active':''}" data-group=""><span>▦</span><span>全部书签</span><span class="count">${data.bookmarks.length}</span></div>`,starred=`<div class="nav-item ${view.starred?'active':''}" data-starred-filter><span>★</span><span>星标书签</span><span class="count">${data.bookmarks.filter(b=>b.starred).length}</span></div>`;$('#groups').innerHTML=all+starred+orderedGroups().filter(groupVisible).map(group=>{const hasChildren=data.groups.some(child=>child.parentId===group.id),collapsed=view.collapsed.has(group.id);const toggle=hasChildren?`<button class="group-toggle" data-toggle-group="${esc(group.id)}" aria-expanded="${!collapsed}" title="${collapsed?'展开':'折叠'}分组">${collapsed?'▸':'▾'}</button>`:'<span class="group-leaf">•</span>';return `<div class="nav-item group-node ${view.group===group.id&&!view.starred?'active':''}" data-group="${esc(group.id)}" draggable="true" style="padding-left:${8+group.depth*13}px">${toggle}<span>${esc(group.name)}</span><span class="group-tools"><span class="drag-handle" title="拖动排序" aria-label="拖动排序">⠿</span><button class="tree-action" data-edit-group="${esc(group.id)}">•••</button><span class="count">${groupCount(group.id)}</span></span></div>`}).join('')}
function renderTags(){const counts=new Map;data.bookmarks.forEach(bookmark=>bookmark.tags?.forEach(tag=>counts.set(tag,(counts.get(tag)||0)+1)));$('#tags').innerHTML=[...counts].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).map(([tag,count])=>`<button class="tag ${view.tag===tag?'active':''}" data-tag="${esc(tag)}">${esc(tag)} · ${count}</button>`).join('')||'<span class="hint">暂无标签</span>';$('#tagNames').innerHTML=[...counts.keys()].map(tag=>`<option value="${esc(tag)}">`).join('');$('#clearTag').hidden=!view.tag}
function filtered(){const allowed=view.group?descendants(view.group):null,q=view.query.trim().toLowerCase();return data.bookmarks.filter(bookmark=>(!view.starred||bookmark.starred)&&(!allowed||allowed.has(bookmark.groupId))&&(!view.tag||bookmark.tags?.includes(view.tag))&&(!q||[bookmark.title,bookmark.url,bookmark.notes,...(bookmark.tags||[]),groupPath(bookmark.groupId)].join(' ').toLowerCase().includes(q))).sort((a,b)=>view.sort==='title'?a.title.localeCompare(b.title):view.sort==='domain'?domain(a.url).localeCompare(domain(b.url)):new Date(b.updatedAt)-new Date(a.updatedAt))}
function renderList(){const rows=filtered(),group=groupById(view.group),list=$('#list');list.classList.toggle('list-view',view.display==='list');$$('[data-view]').forEach(button=>{const active=button.dataset.view===view.display;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});$('#viewTitle').textContent=view.starred?'星标书签':group?groupPath(group.id):view.tag?`标签：${view.tag}`:view.query?'搜索结果':'全部书签';$('#resultMeta').textContent=`${rows.length} 个结果 · 共 ${data.bookmarks.length} 个书签`;$('#activeFilters').innerHTML=[view.starred&&'<span class="filter">仅星标</span>',view.group&&`<span class="filter">分组：${esc(groupPath(view.group))}</span>`,view.tag&&`<span class="filter">标签：${esc(view.tag)}</span>`,view.query&&`<span class="filter">搜索：${esc(view.query)}</span>`].filter(Boolean).join('');list.innerHTML=rows.length?rows.map(bookmark=>{const accent=bookmarkColors[bookmark.color],accentStyle=accent?` style="--bookmark-accent:${accent}"`:'';return `<article class="card ${accent?'has-accent':''}"${accentStyle}><div class="card-head"><div class="favicon">${esc((domain(bookmark.url)[0]||'?').toUpperCase())}</div><div class="card-title"><a href="${esc(bookmark.url)}" target="_blank" rel="noopener">${esc(bookmark.title)}</a><div class="domain">${esc(domain(bookmark.url))}</div></div><div class="card-actions"><button class="color-button" data-color-edit="${esc(bookmark.id)}" aria-label="设置边框颜色" title="设置边框颜色">●</button><button class="star-button ${bookmark.starred?'active':''}" data-star="${esc(bookmark.id)}" aria-label="${bookmark.starred?'取消星标':'添加星标'}" title="${bookmark.starred?'取消星标':'添加星标'}">${bookmark.starred?'★':'☆'}</button><button data-edit="${esc(bookmark.id)}">•••</button></div></div><p class="notes">${esc(bookmark.notes||'')}</p><div class="card-bottom card-meta"><div class="card-tags">${(bookmark.tags||[]).map(tag=>`<button class="tag" data-tag="${esc(tag)}">${esc(tag)}</button>`).join('')}</div><span class="group-path">${esc(groupPath(bookmark.groupId)||'未分组')}</span></div><div class="card-controls"><span><button data-copy="${esc(bookmark.id)}">复制</button><button data-delete="${esc(bookmark.id)}" class="danger">删除</button></span></div></article>`}).join(''):'<div class="empty"><strong>没有匹配的书签</strong><br>可以清除筛选条件或添加新书签</div>'}
function render(){renderGroups();renderTags();renderList();$('#groupPaths').innerHTML=orderedGroups().map(group=>`<option value="${esc(groupPath(group.id))}">`).join('')}

function clearGroupDropTargets(){$$('.group-node').forEach(node=>node.classList.remove('dragging','drop-before','drop-after'))}
function siblingGroupIDs(parentID){return data.groups.filter(group=>!group.deleted&&(group.parentId||'')===parentID).sort((a,b)=>a.order-b.order||a.name.localeCompare(b.name)).map(group=>group.id)}
async function moveGroupBeforeOrAfter(sourceID,targetID,after){const source=groupById(sourceID),target=groupById(targetID);if(sourceID===targetID)return;if(!source||!target||(source.parentId||'')!==(target.parentId||'')){toast('只能在同一层级内拖动排序');return}const ids=siblingGroupIDs(source.parentId||''),original=ids.join(',');ids.splice(ids.indexOf(sourceID),1);const targetIndex=ids.indexOf(targetID);ids.splice(targetIndex+(after?1:0),0,sourceID);if(ids.join(',')===original)return;await api('/api/v1/groups/reorder',{method:'POST',body:JSON.stringify({parentId:source.parentId||'',ids})});await load();toast('分组顺序已保存')}

async function load(){[status,data]=await Promise.all([api('/api/v1/status'),api('/api/v1/state')]);$('#connection').textContent=`${status.deviceFile} · ${data.bookmarks.length} 个书签`;render()}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>node.classList.remove('show'),2200)}
function openBookmark(bookmark={},focusColor=false){const form=$('#bookmarkForm');form.reset();form.elements.id.value=bookmark.id||'';form.elements.title.value=bookmark.title||'';form.elements.url.value=bookmark.url||'';form.elements.groupPath.value=groupPath(bookmark.groupId)||'';form.elements.tagsText.value=(bookmark.tags||[]).join(', ');form.elements.notes.value=bookmark.notes||'';form.elements.color.value=bookmarkColors[bookmark.color]?bookmark.color:'';form.elements.starred.checked=!!bookmark.starred;$('#bookmarkDialog').showModal();if(focusColor)form.elements.color.focus()}
function openGroup(group={}){const form=$('#groupForm');form.reset();form.elements.id.value=group.id||'';form.elements.name.value=group.name||'';form.elements.parentSelect.innerHTML='<option value="">顶层分组</option>'+orderedGroups().filter(g=>g.id!==group.id&&!descendants(group.id||'__none__').has(g.id)).map(g=>`<option value="${esc(g.id)}">${esc(groupPath(g.id))}</option>`).join('');form.elements.parentSelect.value=group.parentId||view.group||'';$('#deleteGroup').hidden=!group.id;$('#groupDialog').showModal()}

$('#groups').onclick=event=>{const toggle=event.target.closest('[data-toggle-group]');if(toggle){event.stopPropagation();const id=toggle.dataset.toggleGroup;view.collapsed.has(id)?view.collapsed.delete(id):view.collapsed.add(id);localStorage.setItem('bookmarkhub.collapsedGroups',JSON.stringify([...view.collapsed]));renderGroups();return}const edit=event.target.closest('[data-edit-group]');if(edit){event.stopPropagation();openGroup(groupById(edit.dataset.editGroup));return}if(event.target.closest('[data-starred-filter]')){view.starred=true;view.group='';render();return}const item=event.target.closest('[data-group]');if(item){view.starred=false;view.group=item.dataset.group;render()}};
$('#groups').ondragstart=event=>{const item=event.target.closest('.group-node');if(!item)return;draggedGroup=item.dataset.group;item.classList.add('dragging');event.dataTransfer.effectAllowed='move';event.dataTransfer.setData('text/plain',draggedGroup)};
$('#groups').ondragover=event=>{const item=event.target.closest('.group-node'),source=groupById(draggedGroup),target=groupById(item?.dataset.group);if(!source||!target||(source.parentId||'')!==(target.parentId||''))return;event.preventDefault();$$('.group-node').forEach(node=>node.classList.remove('drop-before','drop-after'));const after=event.clientY>item.getBoundingClientRect().top+item.getBoundingClientRect().height/2;item.classList.add(after?'drop-after':'drop-before');event.dataTransfer.dropEffect='move'};
$('#groups').ondrop=async event=>{const item=event.target.closest('.group-node');if(!item||!draggedGroup)return;event.preventDefault();const sourceID=draggedGroup,targetID=item.dataset.group,after=item.classList.contains('drop-after');draggedGroup='';clearGroupDropTargets();await moveGroupBeforeOrAfter(sourceID,targetID,after)};
$('#groups').ondragend=()=>{draggedGroup='';clearGroupDropTargets()};
$('#tags').onclick=event=>{const item=event.target.closest('[data-tag]');if(item){view.tag=view.tag===item.dataset.tag?'':item.dataset.tag;render()}};
$('#list').onclick=async event=>{const edit=event.target.closest('[data-edit]')?.dataset.edit,colorEdit=event.target.closest('[data-color-edit]')?.dataset.colorEdit,remove=event.target.closest('[data-delete]')?.dataset.delete,copy=event.target.closest('[data-copy]')?.dataset.copy,star=event.target.closest('[data-star]')?.dataset.star,tag=event.target.closest('[data-tag]')?.dataset.tag;if(tag){view.tag=tag;render();return}if(colorEdit){openBookmark(data.bookmarks.find(b=>b.id===colorEdit),true);return}if(star){const bookmark=data.bookmarks.find(b=>b.id===star);await api('/api/v1/bookmarks/star',{method:'POST',body:JSON.stringify({id:star,starred:!bookmark.starred})});await load();toast(bookmark.starred?'已取消星标':'已添加星标');return}if(edit)openBookmark(data.bookmarks.find(b=>b.id===edit));if(copy){await navigator.clipboard.writeText(data.bookmarks.find(b=>b.id===copy).url);toast('网址已复制')}if(remove&&confirm('确定删除这个书签？')){await api('/api/v1/bookmarks/delete',{method:'POST',body:JSON.stringify({id:remove})});await load();toast('书签已删除')}};
$('#search').oninput=event=>{view.query=event.target.value;renderList()};$('#sort').onchange=event=>{view.sort=event.target.value;renderList()};$('#clearTag').onclick=()=>{view.tag='';render()};$('#newBookmark').onclick=()=>openBookmark();$('#newGroup').onclick=()=>openGroup();
$$('[data-view]').forEach(button=>button.onclick=()=>{view.display=button.dataset.view;localStorage.setItem('bookmarkhub.bookmarkView',view.display);renderList()});
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();$('#search').focus()}});
$$('[data-close]').forEach(button=>button.onclick=()=>$('#'+button.dataset.close).close());

$('#bookmarkForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));await api('/api/v1/bookmarks',{method:'POST',body:JSON.stringify({id:values.id,url:values.url,title:values.title,groupPath:values.groupPath,tags:values.tagsText.split(/[,，]/),notes:values.notes,starred:event.target.elements.starred.checked,color:values.color})});$('#bookmarkDialog').close();await load();toast('书签已保存')};
$('#groupForm').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.target));await api('/api/v1/groups',{method:'POST',body:JSON.stringify({id:values.id,name:values.name,parentId:values.parentSelect})});$('#groupDialog').close();await load();toast('分组已保存')};
$('#deleteGroup').onclick=async()=>{const id=$('#groupForm').elements.id.value;if(id&&confirm('删除这个分组？其中的书签和子分组将移动到上一级。')){await api('/api/v1/groups/delete',{method:'POST',body:JSON.stringify({id})});$('#groupDialog').close();view.group='';await load();toast('分组已删除')}};

$('#settingsButton').onclick=()=>{const form=$('#settingsForm');form.elements.syncDir.value=status.syncDir;form.elements.token.value=status.pairingToken;form.elements.deviceFile.value=status.deviceFile;$('#settingsDialog').showModal()};
$('#copyToken').onclick=async()=>{await navigator.clipboard.writeText($('#settingsForm').elements.token.value);toast('配对令牌已复制')};
$('#settingsForm').onsubmit=async event=>{event.preventDefault();const path=event.target.elements.syncDir.value;await api('/api/v1/settings/sync-dir',{method:'POST',body:JSON.stringify({path})});$('#settingsDialog').close();await load();toast('同步目录已更新')};

$('#importButton').onclick=()=>$('#importDialog').showModal();
$('#importForm').onsubmit=async event=>{event.preventDefault();const file=event.target.elements.file.files[0],mode=event.target.elements.mode.value;if(!file)return;const format=file.name.toLowerCase().match(/\.(xbel|xml)$/)?'xbel':'html';await api('/api/v1/import',{method:'POST',body:JSON.stringify({format,mode,content:await file.text()})});$('#importDialog').close();event.target.reset();await load();toast('导入完成')};
$('#exportHtml').onclick=()=>location.href='/api/v1/export?format=html';$('#exportXbel').onclick=()=>location.href='/api/v1/export?format=xbel';

load().catch(error=>{$('#connection').textContent=error.message;toast(error.message)});setInterval(()=>load().catch(()=>{}),5000);
